# Низкоуровневая настройка pytest

# Количество меток через декораторы не ограничено
# Дополнительно есть встроенные метки xfail(помечает что тест должен упасть) и skip (пометка для пропуска теста)
# Для запуска тестов с маркировкой используй python -m pytest -m smoke (где смоук нужное название метки)
# Для запуска с подробным описанием тестов с маркировкой используй python -m pytest -v -m smoke (где смоук нужное название метки)

[pytest]
# Доп настройка для Soft Asserts (check), которая выводит количество найденных ошибок. По умолчанию - 1, мы ставим - 10
addopts =
    --check-max-tb=10
# Настройка allure для создания директории
    --alluredir=allure-results

markers =
    smoke: smoke tests
    regress: regress tests
    api: api tests
